#!/usr/bin/perl

use GD::Simple;
use Math::Complex ;

#require 'yellows.pl' ;

$RCS_Id = '$RCSfile: gds.pl,v $ $Revision: 1.3 $ ' ;

## 0,0 is top left hand corner.
## New constructor gives us the size of the canvas.
## Template for drawing Fractals.
## JM Mon, Nov 12, 2012  1:28:10 PM
##
## Plot a Nova newton fractal for Z^N = 1
## Use code from: http://www.mathworks.co.uk/matlabcentral/fileexchange/25150-nova-fractal
## Nova fractal is generated by iterating the formula
## 
## z=z - R * f(z)/f '(z) + C
## 
## This is Newton's formula with additional parameters.
## C is constant ,in this fractal C is points of the complex plane
## as in the Mandelbrot set.
## R is relaxation constant ,it is 1 for this fractal.
## For this fractal Z is initialized to -1 for each cycle of iterations.
## JM Thu Jan 23 21:57:07 GMT 2014


$Y_MIN = -1.0 ;
$Y_MAX =  1.0 ;
$X_MIN = -1.0 ;
$X_MAX =  1.0 ;

$y_pixel = 0    ;
$offset  = 0.01 ;
$maxiter = 100  ;
$A       = -0.7 + 0.3*i ;
$const   = -0.19642503 ;
$iter_offset = 95 ;

$X_SIZE = ( $X_MAX - $X_MIN ) / $offset ; 
$Y_SIZE = ( $Y_MAX - $Y_MIN ) / $offset ;

$img = GD::Simple->new( $X_SIZE, $Y_SIZE ) ;

my @color_names = GD::Simple->color_names;

for ( $Y = $Y_MIN ; $Y <= $Y_MAX ; $Y = sprintf ( "%4f", $Y + $offset ) ) {
$x_pixel = 0 ;

	for ( $X = $X_MIN ; $X <= $X_MAX ; $X = sprintf ( "%4f", $X + $offset ) ) {

		#printf "X %2.3f Y %2.3f Z %2.3f Iter: %d \n", $R, $I, $Z, $iter ;
		## print "X $X  Y $Y R2 $R2 I2 $I2 $iter \n" ;
                $iter = 0 ;
		$R0 = $X ;
		$I0 = $Y ;
		$R = $R0 ;
		$Im = $I0 ;
                $C = $R + $Im*i ;
                $Z = -1.0 + 0*i ;

              while ( abs( $Z**2 ) < 2 && ($iter < $maxiter) ) {
                     ## Avoid divide by zero error.

		  if ( $Z ) { 
                     
                     $Z =  $Z**2  + $C + $A ; 
                    
		  }   

                     $iter = $iter + 1 ;

              } # end while

	      #print "$iter " ;

	      plotpixel () ;

	$x_pixel++ ;

	} ## End X.

	#print "\n" ;

	$y_pixel++ ;

} ## End Y.

sub plotpixel {

	if ( $iter <= 2  ) {
		$iter = 186 ;

	} else { 
		$iter %= $iter_offset ; 

	}


	$img->moveTo( $x_pixel, $y_pixel ) ;
	$img->fgcolor( $color_names[ $iter ] ) ;
	$img->lineTo( $x_pixel, $y_pixel ) ;


} ## End comment

# convert into png data
binmode STDOUT ;
print $img->png;
